[package]
name = "holons_client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]
name = "holons_client"

[dependencies]
# General dev-dependencies (platform-agnostic)
derive-new = "0.7"
tracing = "0.1"
#async-trait = "0.1.51"

# MAP Dependencies

holons_core = {path = "../../../shared_crates/holons_core"}
core_types = {path = "../../../shared_crates/type_system/core_types"}
base_types = {path = "../../../shared_crates/type_system/base_types"}
integrity_core_types = {path = "../../../shared_crates/type_system/integrity_core_types"}
holon_dance_builders = {path = "../../../shared_crates/holon_dance_builders"}
