[package]
name = "integrity_core_types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {workspace = true}
derive-new = {workspace = true}
thiserror = {workspace = true}
base_types = {workspace = true}
