[package]
name = "holons_trust_channel"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = {workspace = true}
#serde = { version = "1", features = ["derive"] }
async-trait = {workspace = true}
holons_core = {workspace = true}

