[package]
name = "holochain_receptor"
version = "0.1.0"
edition = "2021"
#edition = "2024"

[dependencies]
tracing = "0.1"
serde_bytes = "*"
async-trait = "0.1"

#holochain dependencies
holochain_client = { version = "0.7.0"}
holochain_types = "0.5"
holochain_conductor_api = { version = "0.5" }
holochain_nonce = { version = "0.5" }

#map dependencies
holons_core = { path = "../../../shared_crates/holons_core" }
holons_client = { path = "../holons_client" }
holons_trust_channel = { path = "../../../shared_crates/holons_trust_channel" }
holons_loader_client = { path = "../../../shared_crates/holons_loader_client" }
core_types = { path = "../../../shared_crates/type_system/core_types" }
base_types = { path = "../../../shared_crates/type_system/base_types" }

