[package]
name = "holons_boundary"
version = "0.1.0"
edition = "2021"

[dependencies]
holons_core = { path = "../holons_core" }
core_types = { path = "../type_system/core_types" }
serde = { version = "1", features = ["derive"] }
