[package]
name = "holons_receptor"
version = "0.1.0"
edition = "2021"
#edition = "2024"

[dependencies]
serde_bytes = "*"
serde_json = "1"
async-trait = "0.1"
tracing = "0.1"
sha2 = "0.10"
hex = "0.4" 


#map dependencies
holons_client = { path = "../holons_client" }
holons_core = { path = "../../../shared_crates/holons_core" }
holochain_receptor = { path = "../holochain_receptor" }
core_types = { path = "../../../shared_crates/type_system/core_types" }

