[package]
name = "shared_validation"
version = "0.1.0"
edition = "2021"

[dependencies]
hdi = { workspace = true }
hdk = { workspace = true }
derive-new = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

shared_types_holon = { workspace = true }