[package]
name = "core_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = { version = "1", features = ["derive"] }
#derive-new = "0.7"
#thiserror = "2"

integrity_core_types = {path = "../integrity_core_types"}
uuid = {version = "1", features = ["serde"]}
