name: CI

on:
  push:
    branches: [main, ci-fix]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.28.3/install

      - uses: cachix/cachix-action@v16
        with:
          name: holochain-ci

      - uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: |
          nix develop --command bash -c "npm ci"

      - name: Test
        run: |
          nix develop --command bash -c "npm test"

#  fmt:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Install nix
#        uses: cachix/install-nix-action@v31
#        with:
#          install_url: https://releases.nixos.org/nix/nix-2.28.3/install
#
#      - name: Check formatting
#        run: |
#          nix develop --command cargo fmt --all --check

#  lint:
#    continue-on-error: true  # ðŸ‘ˆ Make this advisory only
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Install nix
#        uses: cachix/install-nix-action@v31
#        with:
#          install_url: https://releases.nixos.org/nix/nix-2.28.3/install
#
#      - name: Clippy lint
#        run: |
#          nix develop --command cargo clippy --all-features -- -D warnings

  ci_pass:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [ test ]  # ðŸ‘ˆ exclude 'lint'
    steps:
      - name: Check status
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}