name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [develop, main, ci-fix]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      # Minimal system dependencies for Nix
      - name: Install system dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libclang-14-dev libstdc++6 clang

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        run: | 
          nix build
          nix flake check
        with:
          extra_nix_config: |
            experimental-features = flakes nix-command

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name:  holochain-ci

      - name: Build and test
        run: |
          nix develop --command bash -c "npm i && npm t"