[package]
name = "holons"
version = "0.0.1"
edition = "2021"

[lib]
# WASM and non-WASM compatible
crate-type = ["cdylib", "rlib"]
name = "holons"

[dependencies]
# General Dependencies
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.109"

# Holochain Dependencies
hdk = "0.5"


# MAP Dependencies

holons_core = {path = "../../../../shared_crates/holons_core"}
holons_integrity = {path = "../../integrity/holons_integrity"}
holons_guest = {path = "../../../crates/holons_guest"}
