[package]
name = "shared_validation"
version = "0.1.0"
edition = "2021"

[dependencies]

#serde = { version = "1", features = ["derive"] }
#thiserror = "2"


integrity_core_types = {path = "../type_system/integrity_core_types"}
core_types = {path = "../type_system/core_types"}
